"""remove category from notes

Revision ID: 9c43ab508875
Revises: b86487a299cf
Create Date: 2026-08-05 14:07:02.441002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c43ab508875'
down_revision = 'b86487a299cf'
branch_labels = None
depends_on = None


def upgrade():

    # Remove foreign key first
    op.drop_constraint(
        'notes_category_id_fkey',
        'notes',
        type_='foreignkey'
    )

    # Remove category_id column from notes
    op.drop_column(
        'notes',
        'category_id'
    )

    # Remove categories table
    op.drop_table(
        'categories'
    )


    # Make columns not nullable
    op.alter_column(
        'notes',
        'created_at',
        nullable=False
    )

    op.alter_column(
        'users',
        'role',
        nullable=False
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('notes', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('notes_category_id_fkey'), 'notes', 'categories', ['category_id'], ['id'])
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey')),
    sa.UniqueConstraint('name', name=op.f('categories_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    # ### end Alembic commands ###
